title: "bridgingaiandsociety.org"
subtitle: "Bridging AI and Society"
description: "Accessible, interdisciplinary teaching in machine learning and AI — hands-on, discussion-driven, and socially grounded."

url: "https://bridgingaiandsociety.org"
repository: "bridgingaiandsociety/bridgingaiandsociety.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

locale: "en-US"
timezone: "Europe/Zurich"

author:
  name: "Bridging AI and Society Team"

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      classes: wide

plugins:
  - jekyll-feed
  # - jekyll-seo-tag  # Re-enable once we have a proper SEO setup
  - jekyll-sitemap
  - jekyll-include-cache

breadcrumbs: true
markdown: kramdown
highlighter: rouge
