title: "bridgingaiandsociety.org"
subtitle: "Bridging AI and Society"
description: "Experimental particle physicist at CERN | ATLAS | Top-quark physics, machine learning, and new physics searches"

url: "https://bridgingaiandsociety.org"
repository: "bridgingaiandsociety/bridgingaiandsociety.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

locale: "en-US"
timezone: "Europe/Zurich"

author:
  name: "Knut Zoch, Ph.D."

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

breadcrumbs: true
markdown: kramdown
highlighter: rouge
