title: "bridgingaiandsociety.org"
subtitle: "Interdisciplinary Machine Learning Education"
description: "Accessible, interdisciplinary teaching in machine learning and AI — hands-on, discussion-driven, and socially grounded."

url: "https://bridgingaiandsociety.org"
repository: "bridgingaiandsociety/bridgingaiandsociety.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "contrast"

locale: "en-US"
timezone: "Europe/Zurich"

author:
  name: "Bridging AI & Society"
  avatar: "/assets/img/logo.jpg"
  bio: "Interdisciplinary Machine Learning Education by Dr. Christoph Weisser and Dr. Knut Zoch"
  links:
    - label: "About Us"
      icon: "fas fa-fw fa-users"
      url: "/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BridgingAISocietySummerSchools"

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      classes: wide

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

breadcrumbs: true
markdown: kramdown
highlighter: rouge
